import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { El_Messiri } from "next/font/google";
import "./globals.css";
import { Lusitana } from "next/font/google";

const elmsSans = El_Messiri({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-elms-sans",
});

const lusitana = Lusitana({
  subsets: ["latin"],
  weight: ["400", "700"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${elmsSans.variable}`}>
      
      <body
        className={`font-(--font-elms-sans) ${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        {children}
      </body>
    </html>
  );
}